### ISSUE TITLE
ImportError: No module named 'py_ms_cognitive_search'

### ISSUE THREAD

**Issue by sharkwheels** [tristantao/py-ms-cognitive#11]
Hello. Just wondering if this is happening to anyone else, but I'm getting an import error. 

_from py_ms_cognitive_search.py_ms_cognitive_web_search import PyMsCognitiveWebSearch
ImportError: No module named 'py_ms_cognitive_search'_

Any thoughts as to what's up? My program only has the import line: "from py_ms_cognitive import PyMsCognitiveWebSearch" right now.

**Comment by tristantao** [comment]
What version of python? How did you install the module?

**Comment by sharkwheels** [comment]
Python3.5.0. Installed using Pip. Have the dependencies. 

Edit: no import errors in 2.7.10

**Comment by tgalery** [comment]
Same here.  Tested on 3.5.2 via pip.

**Comment by tristantao** [comment]
Closed thx to @tgalery .

**Comment by tgalery** [comment]
Sorry to nag but it might be good to spin a minor release for pip users :-)

**Comment by tristantao** [comment]
I just did :) Version 0.3.1 released a few min ago should have it.
