### ISSUE TITLE
Image filters

### ISSUE THREAD

**Issue by mohsalvi** [tristantao/py-ms-cognitive#17]
How can we add image filters (e.g. Style:Photo+Face:Face) to the query? 
They were in the old version of the code 
https://github.com/tristantao/py-bing-search/blob/master/py_bing_search/py_bing_search.py

**Comment by tristantao** [comment]
You should be able to add the filters via the custom param (which I think you actually made the PR for :)

Thanks for the help, that's merged in now (In the process I changed the custom_params to be a hash).
