### ISSUE TITLE
custom_params

### ISSUE THREAD

**Issue by silentjay** [tristantao/py-ms-cognitive#22]
Getting an issue when using the ImageSearch with custom_params:

`PyMsCognitiveImageSearch(API_KEY,  search_term, custom_params='mkt=en-GB')`

```
py_ms_cognitive_image_search.py", line 39, in _search
packaged_results = [ImageResult(single_result_json) for single_result_json in json_results["value"]]
KeyError: 'value'
```
Without the custom_params it works as expected

**Comment by tristantao** [comment]
I updated with a fix (https://github.com/tristantao/py-ms-cognitive/pull/23) ; the new version will use a hash as the custom_params, i.e. your call will be:

`PyMsCognitiveImageSearch(API_KEY, search_term, custom_params={"mkt" : "en-GB")`

That should work now (and for non-image search too).

**Comment by silentjay** [comment]
Thanks will test and report back soon
