### ISSUE TITLE
Endpoint specification

### ISSUE THREAD

**Issue by pwichmann** [tristantao/py-ms-cognitive#25]
Hi Tristan,

Again, many thanks for your library.
Is there any way to define the MS cognitive endpoint in your library?
This is the one I am supposed to use: https://api.cognitive.microsoft.com/bing/v5.0

Cheers

**Comment by tristantao** [comment]
What do you mean the endpoint? 

All API does use that API, just specialized to the specific service they need. 

Let me know what your expected behavior is.

**Comment by pwichmann** [comment]
My mistake, Tristan. I had thought I need to change the endpoint in your library. But it works just fine. Sorry for bothering you.

Again, your library has been a life saver.

**Comment by tristantao** [comment]
Glad to hear it :)

Feel free to drop other feature request via issues.
