### ISSUE TITLE
Number Of Results.

### ISSUE THREAD

**Issue by Veera619** [tristantao/py-ms-cognitive#30]
How can I see the number of estimated results?
Thank you.

**Comment by rtruxal** [comment]
_(quick FYI: I'm gonna keep with the `README.md` lingo, so if I mention an object that's not in the source, that's where you should look.)_  
### Short Answer:  
Within any of the `PyMsCognitiveXxx` instances, **after** you've made `>=` 1 query with that instance.  

Using the `PyMsCognitiveWebSearch` class it looks like this:   
```py
    search_service.most_recent_json['webPages']['totalEstimatedMatches']
```
### Long-ish answer:  
Depends on the endpoint type you're using but:

1.  Refer back to the README; & do a quick ctrl+f for `search_service`.
2.  **After** you run the `search_service.search()` instance-method, an attr called `search_service.most_recent_json` will get filled with a JSON `dict`.
3. `print search_service.most_recent_json.keys()` will give you a list like:
    ```py
     [u'_type',  
      u'rankingResponse',  
      u'webPages',  
      u'images',  
      u'news',  
      u'relatedSearches']

4. all these^ are additional nested dictionaries. The only one of these with a `totalEstimatedMatches` key is `webPages` (when doing normal web-search.) So:
```py
    search_service.most_recent_json['webPages']['totalEstimatedMatches']
```

5. _Note:_ remember that the other `PyMsCognitiveXxx` objects are calling **completely** different URLs. In other words, `'totalEstimatedMatches'` may not be under `webPages` if you're using the `PyMsCognitiveImageSearch` class.

**Comment by Veera619** [comment]
Worked,
Thank you very much.

**Comment by tristantao** [comment]
Thanks for getting the covered, Rob.
