### ISSUE TITLE
New API keys / subscription key generated for v7.0 do not work

### ISSUE THREAD

**Issue by rcssdy** [tristantao/py-ms-cognitive#33]
This is the error message I receive when using a valid subscription key for v7.0 of the API:

`{ 
  "statusCode": 401, 
  "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." 
} `

I've checked and the endpoint specified in the dashboard is for `v7.0`, however in this wrapper, the endpoint for`v5.0` is being used.

**Comment by rcssdy** [comment]
Since I'm only making use of the web search, I fixed the issue by changing the `SEARCH_WEB_BASE` constant to `https://api.cognitive.microsoft.com/bing/v7.0/search`.

I'm not sure of the implications of changing that here in this wrapper, so I'll leave the issue open for further discussion.

**Comment by saybinem** [comment]
Go to site-packages/py_ms_cognitive/py_ms_cognitive_search/py_ms_cognitive_web_search.py file
Replace SEARCH_WEB_BASE = https://api.cognitive.microsoft.com/bing/v5.0/search with
SEARCH_WEB_BASE = 'https://api.cognitive.microsoft.com/bing/v7.0/search'

**Comment by joraniedemagit** [comment]
Yes, could someone replace that in the library? Currently not working, would be great!

**Comment by guiscaranse** [comment]
The pull request for this issue is here at #34

**Comment by khalsa13** [comment]
Still not working
