### ISSUE TITLE
Issue using custom_params

### ISSUE THREAD

**Issue by ghost** [tristantao/py-ms-cognitive#9]
Receiving this error every time I try to implement a custom parameter:

`Traceback (most recent call last):
  File "show_search_final.py", line 26, in <module>
    search_results = search_service.search(limit=50, format='json')
  File "/Library/Python/2.7/site-packages/py_ms_cognitive/py_ms_cognitive_search/py_ms_cognitive_search.py", line 53, in search
    return self._search(limit, format)
  File "/Library/Python/2.7/site-packages/py_ms_cognitive/py_ms_cognitive_search/py_ms_cognitive_web_search.py", line 37, in _search
    packaged_results = [WebResult(single_result_json) for single_result_json in json_results["webPages"]["value"]]
KeyError: 'webPages'
`

**Comment by tristantao** [comment]
Can you paste what your custom parameter looks like?

**Comment by ghost** [comment]
I've tried two. This one which I'm trying to implement:

  `search_service = PyMsCognitiveWebSearch(API_KEY, search_term, custom_params='&offset=10')
    search_results = search_service.search(limit=50, format='json')`

And this one as a test:
   `search_service = PyMsCognitiveWebSearch(API_KEY, search_term, custom_params="&safesearch=Strict")
    search_results = search_service.search(limit=50, format='json')`

Both give me the same `KeyError: 'webPages'`

**Comment by tristantao** [comment]
Fixed via #14 . Note that this only works on WebSearch. Also please refer README for the details and possible issues with using custom param.
